version: '3.4'

services:
  api:
    build: api
    restart: always
    ports:
    - 127.0.0.1:3001:3001
    volumes:
    - ./api/data:/var/api/data/
    depends_on:
    - kafka

  # KAFKA SERVICES
  zookeeper:
    image: zookeeper:3.4
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    environment:
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_MY_ID: 1
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    links:
    - zookeeper
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/tmp/openwhisk/kafka:/kafka:rw
  apiCouchDB:
    image: apache/couchdb:2.1
    ports:
    - "3002:5984"
    environment:
      COUCHDB_USER: whisk_admin
      COUCHDB_PASSWORD: some_passw0rd
    volumes:
    - ./apiCouchDB/data/:/usr/local/var/lib/couchdb:rw